/* Autogenerated, do not edit. All changes will be undone. */
#include <stdint.h>
namespace res {
extern const uint8_t arrowh[161];
extern const uint8_t arrowv[138];
extern const uint8_t bridgeh[297];
extern const uint8_t bridgev[294];
extern const uint8_t font[561];
extern const uint8_t grassisland[497];
extern const uint8_t grassislandmask[129];
extern const uint8_t islanddone[115];
extern const uint8_t lava[217];
extern const uint8_t lavaisland[492];
extern const uint8_t lavaislandmask[116];
extern const uint8_t lavaislandmenu[465];
extern const uint8_t levelbox[112];
extern const uint8_t levelboxactive[803];
extern const uint8_t levelboxgold[201];
extern const uint8_t rockisland[1879];
extern const uint8_t rockislandmask[129];
extern const uint8_t snow[177];
extern const uint8_t water[217];
}
